# Generated by Django 3.2.16 on 2023-01-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataKomatsu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('horometer', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
