# Generated by Django 3.2.16 on 2023-01-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230113_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('horometer', models.FloatField()),
                ('serie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'datos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DataKomatsu',
        ),
    ]
