# Generated by Django 3.2.16 on 2023-01-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230119_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accelerations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('serie', models.CharField(max_length=60)),
                ('accelx', models.FloatField()),
                ('accely', models.FloatField()),
                ('accelz', models.FloatField()),
            ],
            options={
                'db_table': 'accelerations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FurnanceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('status', models.CharField(max_length=50)),
                ('horometer', models.FloatField()),
                ('serie', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'furnance_data',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Datos',
        ),
    ]
